// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// PARAMETERS
NumericVector PARAMETERS(int n, int d, int iteration);
RcppExport SEXP _CGK_PARAMETERS(SEXP nSEXP, SEXP dSEXP, SEXP iterationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type iteration(iterationSEXP);
    rcpp_result_gen = Rcpp::wrap(PARAMETERS(n, d, iteration));
    return rcpp_result_gen;
END_RCPP
}
// CGKPRESET
List CGKPRESET(int n, int d, NumericVector parameters);
RcppExport SEXP _CGK_CGKPRESET(SEXP nSEXP, SEXP dSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(CGKPRESET(n, d, parameters));
    return rcpp_result_gen;
END_RCPP
}
// CGK
NumericVector CGK(NumericMatrix X, List preset);
RcppExport SEXP _CGK_CGK(SEXP XSEXP, SEXP presetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type preset(presetSEXP);
    rcpp_result_gen = Rcpp::wrap(CGK(X, preset));
    return rcpp_result_gen;
END_RCPP
}
// CGKTESTPRESET
List CGKTESTPRESET(int n, int d, List preset, int iteration);
RcppExport SEXP _CGK_CGKTESTPRESET(SEXP nSEXP, SEXP dSEXP, SEXP presetSEXP, SEXP iterationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< List >::type preset(presetSEXP);
    Rcpp::traits::input_parameter< int >::type iteration(iterationSEXP);
    rcpp_result_gen = Rcpp::wrap(CGKTESTPRESET(n, d, preset, iteration));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CGK_PARAMETERS", (DL_FUNC) &_CGK_PARAMETERS, 3},
    {"_CGK_CGKPRESET", (DL_FUNC) &_CGK_CGKPRESET, 3},
    {"_CGK_CGK", (DL_FUNC) &_CGK_CGK, 2},
    {"_CGK_CGKTESTPRESET", (DL_FUNC) &_CGK_CGKTESTPRESET, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_CGK(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
