# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PARAMETERS <- function(n, d, iteration) {
    .Call(`_CGK_PARAMETERS`, n, d, iteration)
}

CGKPRESET <- function(n, d, parameters) {
    .Call(`_CGK_CGKPRESET`, n, d, parameters)
}

CGK <- function(X, preset) {
    .Call(`_CGK_CGK`, X, preset)
}

CGKTESTPRESET <- function(n, d, preset, iteration) {
    .Call(`_CGK_CGKTESTPRESET`, n, d, preset, iteration)
}

